[[redirects]]
  from = "https://www.psycareer.ru/*"
  to = "https://www.psycareer.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://psycareer.ru/*"
  to = "https://www.psycareer.org/:splat"
  status = 301
  force = true
